### ISSUE TITLE
Haiku available

### ISSUE THREAD

**Issue by jcmag** [tghamm/Anthropic.SDK#16]
Hi,

just to let you know that the haiku model is now available, you should add "claude-3-haiku-20240307" to the AnthropicModels constants ;)

**Comment by dmki** [comment]
But it requires messaging API. You can't just change the model name to Haiku, Sonnet or Opus.

**Comment by tghamm** [comment]
Thanks for the heads up! Saw the announcement, just haven't had a chance to push 2.0.1 yet, but will this weekend 🙂

**Comment by tghamm** [comment]
Update made, thanks again for the reminder!

**Comment by jcmag** [comment]
thanks!
