### ISSUE TITLE
[Feature request] Proxy support

### ISSUE THREAD

**Issue by GilbertoTheMighty** [tghamm/Anthropic.SDK#18]
Hello. Could you please add proxy support to this api. 
```
var handler = new HttpClientHandler
{
    Proxy = new WebProxy
    {
        Address = new Uri("socks5://8.8.8.8:123"),
        Credentials = new NetworkCredential("user", "pass")
    }
};

client = new HttpClient(handler);
```

**Comment by tghamm** [comment]
Yeah I think that can be supported, will try and work on it in the next couple of days.

**Comment by gluip** [comment]
@GilbertoTheMighty  You can use the HttpClientHandlerFactory for that. Just inject it into the AnthropicClient.

**Comment by tghamm** [comment]
Following in a few other libraries footsteps, I switched to `HttpClient` (and removed a dep in the process) so this can be a little more targeted now than with a Factory.
