### ISSUE TITLE
Role is still of type string in MessageResponse and StreamMessage classes

### ISSUE THREAD

**Issue by sibbl** [tghamm/Anthropic.SDK#31]
Hi,

thanks a lot for all the recent refactoring to support functions! I just updated my code base and found the following inconsistency:

While most `Role` properties changed from `string` to `RoleType`, the `Role` properties in the `MessageResponse` and `StreamMessage` classes are still of type `string`.

As I suppose the values can also just be "user" or "assistant", the `RoleType` enum could be used there as well, couldn't it?

As a workaround, I now have my own comparison utility.

**Comment by tghamm** [comment]
Correct - simple oversight, I'll have a release out in a couple of hours to address this.  Thanks for the feedback @sibbl!

**Comment by tghamm** [comment]
New version is out!  Thanks again.

**Comment by sibbl** [comment]
Thanks for the very fix reply and fix!
