### ISSUE TITLE
Surface response headers in result?

### ISSUE THREAD

**Issue by pclaar** [tghamm/Anthropic.SDK#34]
Is there a way to surface the response headers in the AnthropicClient? See[ https://docs.anthropic.com/claude/reference/rate-limits for a list of Res](https://docs.anthropic.com/claude/reference/rate-limits#response-headers)

With this we can see what's going on when we hit a rate limit.

**Comment by tghamm** [comment]
These have now been surfaced in the response from the API in 4.0.0.
