### ISSUE TITLE
[question]  about function calling

### ISSUE THREAD

**Issue by sabbadino** [tghamm/Anthropic.SDK#39]
Hi, I have raw JSON schema strings extracted from an open api doc ..
Is it possible setup a function with a raw string ? Is it possible to get the raw JSON response (and function name) from the LLM ? Thanks

**Comment by tghamm** [comment]
Yes, take a look at the final example in the README, where a c# schema is serialized into a JSON string and then declared as a function, and then the raw response is read.  There are similar examples in the unit tests.
