### ISSUE TITLE
Feature request: Prompt caching

### ISSUE THREAD

**Issue by TIAcode** [tghamm/Anthropic.SDK#45]
Anthropic just introduced [prompt caching](https://www.anthropic.com/news/prompt-caching), which would be incredibly useful for a ton of applications, but I don't think there's  a way to currently use it whti Anthropic.SDK.

**Comment by tghamm** [comment]
I've got it pretty much working, just pondering some additional tests to make sure I don't regress anything.

**Comment by tghamm** [comment]
Support has been added, check out the readme and/or unit tests for examples.  Hope it helps!
